
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 09 12:52:06 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 6;
  public static final int LEFTBOX = 23;
  public static final int PLUS = 8;
  public static final int SEMI = 17;
  public static final int CHAR = 5;
  public static final int LEFTPAR = 21;
  public static final int RIGHTBOX = 24;
  public static final int END = 14;
  public static final int RIGHTPAR = 22;
  public static final int WRITE = 7;
  public static final int ID = 15;
  public static final int OF = 13;
  public static final int SUB = 9;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int DIV = 11;
  public static final int DOTDOT = 18;
  public static final int CONST = 16;
  public static final int CASE = 12;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int INTEGER = 3;
  public static final int RIGHTBRACE = 26;
  public static final int LEFTBRACE = 25;
  public static final int REAL = 4;
  public static final int MUL = 10;
}

